### ISSUE TITLE
Code Issue Review

### ISSUE THREAD

**Issue by thomad74** [wattob/sideScrollerGame#1]
### Date of the Review: 8 November 2018

- Inspection rate: about 5-10 lines per minute for a total of 10 minutes
- Defect rate: no obvious bugs in the code that prevented it from running correctly
- Defect density: n/a

### Checklist

- [ ] Code Formatting
Choose a specific style guide to follow, as this seems to be kind of all over the place with regards to style.
- [x] Coding Best Practices
- [x] Code Readability
- [x] Code Testability
- [x] Code Reliability
- [x] Usability

**Comment by wattob** [comment]
Thank you for the feedback! I implemented a .travis.yml file that checks every push to the project repository to see if it adheres to the PEP8 style guide and standards. I have also checked the writing using the Proselint tool.
